name: Extra Events
version: 1.4.7 b1
author: coldandtired
main: me.coldandtired.extra_events.ExtraEvents
description: Adds a few events not found in Bukkit
website: coldandtired.binhoster.com
softdepend: [WorldGuard]