name: Extra Events
version: 1.4.5 b1
author: coldandtired
main: me.coldandtired.extra_events.Extra_events
description: Adds a few events not found in Bukkit
website: coldandtired.binhoster.com
softdepend: [WorldGuard]